name: Node.js Build

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']

jobs:
    DaemonCI:
        name: Daemon CI
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./daemon

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
                  cache-dependency-path: ./daemon/package-lock.json
            - name: Install clean state
              run: npm ci
            - name: Building project
              run: npm run build --if-present
            - name: Lint using ESLint
              run: npm run lint --if-present
